version: '3.8'
services:
  discovery-server:
    image: taghreedhamdy/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - my-network

  config-server:
    image: taghreedhamdy/config-server:latest
    container_name: config-server
    ports:
      - "9191:9191"
    networks:
      - my-network
  gateway:
    image: taghreedhamdy/gateway:latest
    container_name: gateway
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:9191/
      SPRING_CLOUD_DISCOVERY_ENABLED: true
      EUREKA_SERVER: http://discovery-server:8761/eureka/
    ports:
      - "8600:8600"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - my-network
  employee-service:
    image: taghreedhamdy/employee-service:latest
    container_name: employee-service
    ports:
      - "9000:9000"
    networks:
      - my-network



  frontend:
    image: taghreedhamdy/frontend:16.2.11
    container_name: frontend
    ports:
      - "4200:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
