eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:4200"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowCredentials: false
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/*

#        - id: employee-service-swagger
#          uri: http://localhost:9000/employee-service/swagger-ui/index.html
#          predicates:
#            - Path=/employee-service/swagger-ui/**
server:
  port: 8600

