spring:
  application:
    name: employee-service
  config:
    import: optional:configserver:http://localhost:8761
  datasource:
    url: jdbc:sqlite:employees.db
    driver-class-name: org.sqlite.JDBC
    username: pxp
    password: password

  jpa:
    database-platform: com.stc.employeeservice.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    org.springframework.web.cors: DEBUG



server:
  port: 9000


eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
